#!/bin/sh

data="$(mmsg get focusing-client)"
x="$(printf '%s' "${data}" | jq .x)"
y="$(printf '%s' "${data}" | jq .y)"
w="$(printf '%s' "${data}" | jq .width)"
h="$(printf '%s' "${data}" | jq .height)"
geometry="$(printf '%d,%d %dx%d' "$x" "$y" "$w" "$h")"
grim -g "${geometry}" -t ppm - | satty -f -

