#!/bin/sh
ocr_lang="$(tesseract --list-langs | tail -n +2 | fuzzel -d -p "Select OCR language")"
grim -g "$(slurp)" -t ppm - | tesseract -l "${ocr_lang}" - - | wl-copy
notify-send "Selected text was copied to clipboard!"

