#!/bin/sh

xdg_data="${XDG_DATA_HOME:-${HOME}/.local/share}"
s6_srcdir="$xdg_data/s6" # directory with inital s6 configs, svcs, and databases
s6_storelist="${s6_srcdir}/sv:${s6_srcdir}/bundles:${s6_srcdir}/sv-nogit" # list of sources (services and bundles) separated by colon
s6_compdir="$s6_srcdir/rc/compiled" # compiled database directory
s6_repodir="$s6_srcdir/repository" # s6-rc-repo* commands repository
s6_frontend_conf="$s6_srcdir/s6-frontend.conf" # path to s6-frontend configuration file
s6_runtime_dir="$XDG_RUNTIME_DIR/s6" # s6 data folder (scandir, livedir, logs, etc)
s6_scandir="$s6_runtime_dir/service" # s6 scandir
s6_livedir="$s6_runtime_dir/s6-rc" # s6-rc livedir
s6_svdirs="$s6_livedir/servicedirs" # s6-rc servicedir
s6_stmpdir="$s6_runtime_dir/stmp" # s6-frontend runtime data and temp files
s6_logger_dir="$s6_scandir/s6-svscan-log" # servicedir of catch-all logger
s6_logger_fifo="$s6_logger_dir/fifo" # fifo where all uncaught logs will go

if [ -z "$S6_FRONTEND_CONF" ]; then
    echo "S6_FRONTEND_CONF environment variable is empty. Please add to your environment:"
    echo
    echo 'export S6_FRONTEND_CONF="$XDG_DATA_HOME/s6/s6-frontend.conf"'
    echo
    exit 1
fi

export S6_FRONTEND_CONF="$s6_frontend_conf"

boot_tree() {
    if s6-svscanctl -z "${s6_scandir}" 2>/dev/null; then
        echo "s6-svscan is already running on ${s6_scandir}, doing nothing"
        exit 1;
    fi
    rm -f "${s6_livedir}"
    rm -rf "${s6_scandir}"

    mkdir -p "$s6_scandir"
    mkdir -p "$s6_runtime_dir/log"
    cp -rL "$s6_srcdir/s6-svscan-log" "$s6_scandir"
    mkfifo "$s6_logger_fifo"
    
    setsid -f \
    fdmove -c 4 1 \
    redirfd -wnb 1 "$s6_logger_fifo" \
    fdmove -c 2 1 \
    envfile -I "$s6_srcdir/config/global.conf" \
    s6-svscan -d 4 "$s6_scandir" | read -r _

    # TODO replace  the following 2 lines with s6 system boot once s6-rc-init -b is fixed
    s6-rc-init -c "$s6_compdir" -l "$s6_livedir" "$s6_scandir"
    s6 live start-everything
}

tear_tree(){
    s6 process stop -w s6-svscan-log # stop the catch-all logger, or else it will ignore s6 shutdown and continue to run
    s6-svscanctl -t "$s6_scandir" # shut down the s6 tree
}

generate_s6_frontend_config(){
    echo "Writing s6-frontend config to $s6_frontend_conf"
    {
        echo "scandir = $s6_scandir"
        echo "livedir = $s6_livedir"
        echo "repodir = $s6_repodir"
        echo "bootdb = $s6_compdir"
        echo "stmpdir = $s6_stmpdir"
        echo "storelist = $s6_storelist"
    } > "$s6_frontend_conf"
}

db_diff(){
    if ! s6-rc -l "$s6_livedir" diff 2>&1 > /dev/null; then
        echo "s6-rc is not alive in $s6_livedir directory!"
        exit 1
    fi
    echo "Displaying what services will be stopped, and what services will be started"
    echo
    s6-rc-update -n -l "$s6_livedir" "${s6_repodir}/compiled/current"
    echo
}

repo_init(){
    if [ -d "$s6_repodir" ]; then
        echo "${s6_repodir} already exists!"
        exit 1
    fi
    echo "Creating repository at ${s6_repodir}"
    echo
    s6 -v2 repository init
    echo
    echo "Adding all services from 'current-set-init' bundle to 'enabled' rx (it's ok to fail here if the bundle does not exist)"
    echo
    s6 -v2 set enable -I pull current-set-init
    echo
    echo "Committing changes"
    echo
    s6 -v2 set commit
    echo
    if [ ! -d "$s6_compdir" ]; then
        echo "${s6_compdir} does not exist, installing s6-rc database without calling s6-rc-update"
        echo
        s6 -v2 live install --init
    elif  ! s6-rc -l "$s6_livedir" diff; then
        echo "s6-rc is not live, installing s6-rc database without calling s6-rc-update"
        echo
        s6 -v2 live install --init
    else
        echo "${s6_compdir} exists and s6-rc is alive, installing s6-rc database and calling s6-rc-update"
        echo "WARNING!!! It will affect the current s6 state and MAY stop some of your services!!!"
        db_diff
        echo "Enter YES in uppercase to confirm, enter anything else to decline"
        read -r apply
        if [ "${apply}" != "YES" ]; then
          echo "No changes were made to the s6-rc database. Please run s6 live install manually to finish the repo initialization"
          exit 1
        fi
        s6 -v2 live install
    fi
    echo
    echo "Repo initialization finished without errors"
    echo
}

if [ "$1" != "genconfig" ] && [ ! -e "$s6_frontend_conf" ]; then
    echo "File $s6_frontend_conf is missing. Please run 'usertree genconfig' first"
    exit 1
fi

case "$1" in
    genconfig)
        generate_s6_frontend_config
    ;;
    boot)
        boot_tree 
    ;;
    tear)
        tear_tree
    ;;
    diff)
        db_diff
    ;;
    repoinit)
        repo_init
    ;;
    *)
        cat << EOF

Usage: usertree [command] <args>
  genconfig - generate s6-frontend config
  boot - boot usertree
  tear - teardown usertree
  diff - show what services will be stopped/started if you install the current set
  repoinit - init s6-rc repository

EOF
    ;;
esac

