#!/bin/sh

readonly table="%-70s %-10s %-10s %-14s %-5s"
readonly dtable="%-67s %-10s %-10s %-14s %-5s"

xdg_data="${XDG_DATA_HOME:-${HOME}/.local/share}"
s6_srcdir="$xdg_data/s6" # directory with inital s6 configs, svcs, and databases
s6_storelist="${s6_srcdir}/sv:${s6_srcdir}/bundles" # list of sources (services and bundles) separated by colon
s6_compdir="$s6_srcdir/rc/compiled" # compiled database directory
s6_repodir="$s6_srcdir/repository" # s6-rc-repo* commands repository
s6_dir="$XDG_RUNTIME_DIR/s6" # s6 data folder (scandir, livedir, logs, etc)
s6_scandir="$s6_dir/service" # s6 scandir
s6_livedir="$s6_dir/s6-rc" # s6-rc livedir
s6_svdirs="$s6_livedir/servicedirs" # s6-rc servicedir
s6_stmpdir="$s6_dir/stmp" # s6-frontend runtime data and temp files
s6_logger_dir="$s6_scandir/s6-svscan-log" # servicedir of catch-all logger
s6_logger_fifo="$s6_logger_dir/fifo" # fifo where all uncaught logs will go

s6_user() {
    s6 -v 2 --color=auto -s "$s6_scandir" -l "$s6_livedir" -r "$s6_repodir" -c "$s6_compdir" --stmpdir="$s6_stmpdir" --storelist="${s6_storelist}" "$@"
}

boot_tree() {
    if s6-svscanctl -z "${s6_scandir}" 2>/dev/null; then
        echo "s6-svscan is already running on ${s6_scandir}, doing nothing"
        exit 1;
    fi
    rm -f "${s6_livedir}"
    rm -rf "${s6_scandir}"

    mkdir -p "$s6_scandir"
    mkdir -p "$s6_dir/log"
    cp -rL "$s6_srcdir/s6-svscan-log" "$s6_scandir"
    mkfifo "$s6_logger_fifo"
    
    setsid -f \
    fdmove -c 4 1 \
    redirfd -wnb 1 "$s6_logger_fifo" \
    fdmove -c 2 1 \
    envfile -I "$s6_srcdir/config/global.conf" \
    s6-svscan -d 4 "$s6_scandir" | read -r _

    # TODO replace  the following 2 lines with s6_user system boot once s6-rc-init -b is fixed
    s6-rc-init -c "$s6_compdir" -l "$s6_livedir" "$s6_scandir"
    s6_user live start-everything
}

tear_tree(){
    s6-svc -d "$s6_logger_dir" # stop the catch-all logger first, or else it will ignore s6 shutdown and continue to run
    s6-svscanctl -t "$s6_scandir" # shut down the s6 tree
    rm -f "${s6_livedir}"
    rm -rf "${s6_scandir}"
}

repo_init(){
    if [ -d "$s6_repodir" ]; then
        echo "${s6_repodir} already exists!"
        exit 1
    fi
    echo "Creating repository at ${s6_repodir}"
    echo
    s6_user repository init
    echo
    echo "Adding all services from 'current-set-init' bundle to 'enabled' rx (it's ok to fail here if the bundle does not exist)"
    echo
    s6_user set enable -I pull current-set-init
    echo
    echo "Committing changes"
    echo
    s6_user set commit
    echo
    if [ ! -d "$s6_compdir" ]; then
        echo "${s6_compdir} does not exist, installing s6-rc database without calling s6-rc-update"
        echo
        s6_user live install --init
    elif  ! s6-rc -l "$s6_livedir" diff; then
        echo "s6-rc is not live, installing s6-rc database without calling s6-rc-update"
        echo
        s6_user live install --init
    else
        echo "${s6_compdir} exists and s6-rc is alive, installing s6-rc database and calling s6-rc-update"
        echo "WARNING!!! It will affect the current s6 state and MAY stop some of your services!!!"
        echo "Displaying what services will be stopped, and what services will be started"
        echo
        s6-rc-update -n -l "$s6_livedir" "${s6_repodir}/compiled/current"
        echo
        echo "Enter YES in uppercase to confirm, enter anything else to decline"
        read -r apply
        if [ "${apply}" != "YES" ]; then
          echo "No changes were made to the s6-rc database. Please run s6 live install manually to finish the repo initialization"
          exit 1
        fi
        s6_user live install
    fi
    echo
    echo "Repo initialization finished without errors, add the following alias to your shell and you are good to go:"
    echo
    cat << EOF
alias s6='s6 -v 2 --color=auto -s "${XDG_RUNTIME_DIR}/s6/service" -l "${XDG_RUNTIME_DIR}/s6/s6-rc" -r "${XDG_DATA_HOME}/s6/repository" -c "${XDG_DATA_HOME}/s6/rc/compiled" --stmpdir="${XDG_RUNTIME_DIR}/s6/s6-frontend" --storelist="${XDG_DATA_HOME}/s6/sv:${XDG_DATA_HOME}/s6/bundles"
EOF
   echo
}

case "$1" in
    boot)
        boot_tree 
    ;;
    tear)
        tear_tree
    ;;
    repoinit)
        repo_init
    ;;
    *)
        cat << EOF

Usage: usertree [command] <args>
  boot - boot usertree
  tear - teardown usertree
  repoinit - init s6-rc repository

EOF
    ;;
esac

