[engine]
# Because no systemd
cgroup_manager = "cgroupfs"
image_copy_tmp_dir = "/data/senderman/podman-tmp"

[network]
pasta_options = ["-a", "172.31.0.2/24", "-g", "172.31.0.1", "--dns-forward", "172.32.0.3"]

[containers]
userns = "auto"

