[storage]
graphroot = "/data/senderman/podman"
driver = "overlay"

# HDD is too slow, wanna use overlayfs instead of native because userns=auto
# https://github.com/podman-container-tools/podman/blob/main/docs/tutorials/performance.md#choosing-a-storage-driver
[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"

