#!/usr/bin/env bash

shopt -s nullglob globstar

menu_name="Get password"

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

passcmd="pass"
if [[ $1 == "otp" ]]; then
  menu_name="Get OTP code"
  passcmd="pass otp"
fi

extraction_cmd="cat"
if [[ $1 == "user" ]]; then
  menu_name="Get username"
  extraction_cmd='sed 2p;d'
fi
echo "${extraction_cmd}"

if [[ -n $WAYLAND_DISPLAY ]]; then
	xdotool="wtype -"
  dmenu="fuzzel -d"
elif [[ -n $DISPLAY ]]; then
	xdotool="xdotool type --clearmodifiers --file -"
else
  dmenu="rofi -dmenu"
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | $dmenu -p "${menu_name}: ")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	$passcmd show -c "$password" 2>/dev/null
else
	$passcmd show "$password" | $extraction_cmd | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
fi
