#!/bin/sh

if [ -n "$WAYLAND_DISPLAY" ]; then
  dmenu="fuzzel -d"
elif [ -n "$DISPLAY" ]; then
  dmenu="rofi -dmenu"
else
  echo "Error: No Wayland or X11 display detected" 1>&2
  exit 1
fi
selection=$(printf "%s\n" "teardown usertree" poweroff reboot hibernate suspend | $dmenu -p "Shutdown menu: ")
if [ "${selection}" == "teardown usertree" ]; then
  sync
  usertree t
elif [ -n "${selection}" ]; then
  sync
  loginctl "${selection}"
fi

