#!/bin/sh

if [ -z "${SCREENDIR}" ]; then
    echo '$SCREENDIR environment variable is not specified' 1>&2
    exit 1
fi

if [ -n "$WAYLAND_DISPLAY" ]; then
  dmenu="fuzzel -d"
elif [ -n "$DISPLAY" ]; then
  dmenu="rofi -dmenu"
else
	echo "Error: No Wayland or X11 display detected" 1>&2
	exit 1
fi

if [ ! -d "${SCREENDIR}" ]; then
  notify-send "No screen session directory found!"
  exit 0
fi

selection="$(ls "${SCREENDIR}" | $dmenu -p "screens: ")"
[ -n "$selection" ] && footclient screen -r "$selection"

