#!/bin/sh

screendir="${SCREENDIR:-${XDG_RUNTIME_DIR}/screens}"

if [ -n "$WAYLAND_DISPLAY" ]; then
  dmenu="fuzzel -d"
elif [ -n "$DISPLAY" ]; then
  dmenu="rofi -dmenu"
else
	echo "Error: No Wayland or X11 display detected" 1>&2
	exit 1
fi

if [ ! -d "${screendir}" ]; then
  notify-send "No screen session directory found!"
  exit 0
fi

selection="$(fd . --base-directory "${screendir}" | $dmenu -p "screens: ")"
[ -n "$selection" ] && "${TERMCMD:-footclient}" screen -r "$selection"

