#!/bin/sh

tty="$(tty)"
tty="${tty#/dev/tty}"

export XAUTHORITY="$HOME/.Xauthority"
export DISPLAY=":$tty"

(~/.s6/sv/xorg-srv/run 4>&1 1>/dev/null &) | read xorg_ready

s6_compdir="$HOME/.s6/rc/compiled" # compiled database directory
s6_dir="$XDG_RUNTIME_DIR/s6" # s6 data folder (scandir, livedir, logs, etc)
s6_scandir="$s6_dir/service" # s6 scandir
s6_livedir="$s6_dir/s6-rc" # s6-rc livedir
s6_logger_fifo="$s6_scandir/s6-svscan-log/fifo" # fifo where all uncaught messages will go

mkdir -p "$s6_scandir"
mkdir -p "$s6_dir/log"
cp -rL "$HOME/.s6/s6-svscan-log" "$s6_scandir"
mkfifo "$s6_logger_fifo"

setsid -f \
    fdmove -c 4 1 \
    redirfd -wnb 1 "$s6_logger_fifo" \
    fdmove -c 2 1 \
    envfile ~/.s6/config/env.conf \
    s6-svscan -d 4 "$s6_scandir" | read s6_ready

s6-rc-init -c "$s6_compdir" -l "$s6_livedir" "$s6_scandir"
s6-rc -l "$s6_livedir" start default

