#!/bin/sh

if [ -n "$WAYLAND_DISPLAY" ]; then
  text="$(wl-paste -p)"
  copycmd="wl-copy"
elif [ -n "$DISPLAY" ]; then
  text="$(xsel -o)"
  copycmd="xsel -ib"
else
  echo "Error: No Wayland or X11 display detected" 1>&2
fi
translated="$(trans -b :ru "$text")"
footclient -a footfloating -T Translation -W 70x15 sh -c "gum confirm --prompt.foreground='#FFFFFF'  --affirmative='Copy to clipboard' --negative='Dismiss' \"${translated}\" && printf '%s' \"${translated}\" | \"${copycmd}\" "
#zenity --info --title "Translation" --text "$translated" &

