#!/bin/sh

if [ -n "$WAYLAND_DISPLAY" ]; then
  text="$(wl-paste -p)"
  copycmd="wl-copy"
elif [ -n "$DISPLAY" ]; then
  text="$(xsel -o)"
  copycmd="xsel -ib"
else
  echo "Error: No Wayland or X11 display detected" 1>&2
fi
translated="$(trans -b :ru "$text")"

action="$(notify-send -a 'translation' -A dismiss=Dismiss -A copy='Copy to clipboard' 'Translation' "${translated}")"

if [ "$action" = "copy" ]; then
    printf "%s" "${translated}" | $copycmd
fi

