[global]
  ipa: 127.0.0.1/32,192.168.0.0/16
  hist: ~/.cache/copyparty
  ftp: 2222
  usernames
  http-only
  no-crt
  no-del
  no-mv
  no-acode
  xvol
  xdev
  vol-nospawn
  vol-or-crash

% accounts.conf

[/home]
  ~
  accs:
    a: senderman

[/shared]
  ~/Documents/shared
  accs:
    r: *
    rw: guest,senderman

[/content]
  ~/Content
  accs:
    r: *
  flags:
    grid


[/music]
  ~/Music
  accs:
    r: *
  flags:
    grid

