# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#181f2b"

# Main text color
theme[main_fg]="#c5c8c6"

# Title color for boxes
theme[title]="#c5c8c6"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8A6EDE"

# Background color of selected items
theme[selected_bg]="#6A99FF"

# Foreground color of selected items
theme[selected_fg]="#222222"

# Color of inactive/disabled text
theme[inactive_fg]="#222222"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#D0D2D0"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#34B45A"

# Cpu box outline color
theme[cpu_box]="#8A6EDE"

# Memory/disks box outline color
theme[mem_box]="#34B45A"

# Net up/down box outline color
theme[net_box]="#FF6B6B"

# Processes box outline color
theme[proc_box]="#6A99FF"

# Box divider line and small boxes line color
theme[div_line]="#222222"

# Temperature graph colors
theme[temp_start]="#AD8CFF"
theme[temp_mid]="#E7BC63"
theme[temp_end]="#ff6b6b"

# CPU graph colors
theme[cpu_start]="#AD8CFF"
theme[cpu_mid]="#E7BC63"
theme[cpu_end]="#ff6b6b"

# Mem/Disk free meter
theme[free_start]="#AD8CFF"
theme[free_mid]="#E7BC63"
theme[free_end]="#ff6b6b"

# Mem/Disk cached meter
theme[cached_start]="#AD8CFF"
theme[cached_mid]="#E7BC63"
theme[cached_end]="#ff6b6b"

# Mem/Disk available meter
theme[available_start]="#AD8CFF"
theme[available_mid]="#E7BC63"
theme[available_end]="#ff6b6b"

# Mem/Disk used meter
theme[used_start]="#AD8CFF"
theme[used_mid]="#E7BC63"
theme[used_end]="#ff6b6b"

# Download graph colors
theme[download_start]="#AD8CFF"
theme[download_mid]="#E7BC63"
theme[download_end]="#ff6b6b"

# Upload graph colors
theme[upload_start]="#AD8CFF"
theme[upload_mid]="#E7BC63"
theme[upload_end]="#ff6b6b"

