# Borders
borderpx=3
no_border_when_single=1
rootcolor=0x201b14ff
bordercolor=0x242757ff
focuscolor=0x9b98ffff
maximizescreencolor=0x89aa61ff
urgentcolor=0xbd2c40ff
scratchpadcolor=0x90619eff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff
dropcolor=0x17192588

# Overview Jump Mode
jump_label_decorate_fg_color=0xae8bffff
jump_label_decorate_bg_color=0x171925ff
jump_label_decorate_border_color=0xae8bffff
jump_label_decorate_border_width=3
jump_label_decorate_font_desc=Noto Sans 16

# Groups

group_bar_decorate_fg_color=0xae8bffff
group_bar_decorate_bg_color=0x272935ff
group_bar_decorate_focus_fg_color=0xae8bffff
group_bar_decorate_focus_bg_color=0x171925ff
group_bar_decorate_border_color=0xae8bffff
group_bar_decorate_border_width=3
group_bar_decorate_font_desc=Noto Sans 16

# Animation Configuration
animations=1
layer_animations=1
animation_type_open=zoom
animation_type_close=slide
tag_animation_direction=1

# Master-Stack Layout Setting
default_mfact=0.50
smartgaps=1

# Gaps
gappoh=0
gappov=0

# Overview Setting
enable_hotarea=0
overviewgappi=5
overviewgappo=5
ov_tab_mode=1

# Misc
focus_on_activate=0
drag_tile_to_tile=1
drag_tile_small=1
axis_bind_apply_timeout=0
warpcursor=0
view_current_to_back=1

# keyboard
xkb_rules_layout=us,ru
xkb_rules_options=grp:win_space_toggle
bind=SUPER,x,spawn,s6 live start fcitx mozc
bind=SUPER+SHIFT,x,spawn,s6 live stop fcitx mozc

