server 0.ru.pool.ntp.org iburst
server 1.ru.pool.ntp.org iburst
server 2.ru.pool.ntp.org iburst
server 3.ru.pool.ntp.org iburst

# Record OS clock drift
driftfile /var/lib/chrony/drift

# Record sources measurement history
dumpdir /var/lib/chrony

# Record RTC drift
rtcfile /var/lib/chrony/rtc

# Update RTC if the error between system and RTC is lager then 30 seconds
rtcautotrim 30

# RTC is UTC+0, not localtime
rtconutc

# This would step the system clock if the adjustment is larger than 1.0 seconds,
# but only in  the first three clock updates.
makestep 1.0 3

leapseclist /usr/share/zoneinfo/leap-seconds.list

