[metadata]
name = "cdcmp"
description = "Channel for cd autocompletion"
requirements = ["fd", "sd", "lsd"]

[source]
command = ["fd --hidden -t d -t l --max-depth=1 | sd '/$' ''"]

[preview]
command = "lsd --color always --icon always '{}'"

