[metadata]
name = "cheat"
description = "A channel to view cheatsheets"
requirements = ["bat", "fd"]

[source]
command = "fd -t f . ~/.config/cheat/cheatsheets"

[preview]
command = "bat --color=always -l bash '{}'"

[keybindings]
enter = "actions:print"

[actions.print]
description = "Print the selected cheatsheet"
command = "bat --color=always -l bash '{}'"
mode = "execute"

