[metadata]
name = "s6"
description = "A channel to control s6 usertree bundles"
requirements = ["s6-rc", "s6-rc-db"]

[source]
command = "s6-rc-db -c ~/.local/share/s6/rc/compiled list bundles"

[preview]
command = "s6-rc-db -c ~/.local/share/s6/rc/compiled contents '{}'"

[keybindings]
ctrl-u = "actions:start_bundle"
ctrl-d = "actions:stop_bundle"

[actions.start_bundle]
description = "Start services in the selected bundles"
command = "s6-rc -l $XDG_RUNTIME_DIR/s6/s6-rc start {}"

[actions.stop_bundle]
description = "Stop services in the selected bundles"
command = "s6-rc -l $XDG_RUNTIME_DIR/s6/s6-rc stop {}"

