#!/bin/sh

touchpad="DELL09E1:00 04F3:30CB Touchpad"

xrdb ${HOME}/.Xresources

xinput set-prop "$touchpad" "libinput Tapping Enabled" 1
xinput set-prop "$touchpad" "libinput Natural Scrolling Enabled" 1

# Set layout switch to Win+Space
setxkbmap -layout us,ru -option "grp:win_space_toggle"

# Configure screen locker
xset s on
xset s 600 # lock screen after 10 minutes of inactivity
